apiVersion: v1
kind: Service
metadata:
    name: idurar-backend
spec:
    type: ClusterIP
    selector:
        app: idurar-backend
    ports:
      - port: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: idurar-backend
spec:
    selector:
        matchLabels:
            app: idurar-backend
    replicas: 2
    template:
        metadata:
            labels:
                app: idurar-backend
        spec:
            imagePullSecrets:
              - name: cr-classic-registry-secret
            containers:
              - name: idurar-backend
                image: cr.classic.duckdns.org:58083/idurar-backend:latest
                ports:
                  - containerPort: 8888
                env:
                  - name: DATABASE
                    value: "mongodb://root:example@mongo:27017"
                  - name: REDIS_HOST
                    value: valkey
                  - name: REDIS_PORT
                    value: 6379
                  - name: PUBLIC_SERVER_FILE
                    value: https://backend.deployment-risks.duckdns.org:30045
                  - name: JWT_SECRET
                    valueFrom: 
                        secretKeyRef:
                            name: backend-env
                            key: JWT_SECRET
                  - name: RESEND_API
                    valueFrom: 
                        secretKeyRef:
                            name: backend-env
                            key: RESEND_API

