apiVersion: v1
kind: Service
metadata:
    name: mongo
spec:
    type: ClusterIP
    selector:
        app: mongo
    ports:
      - port: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: mongo
spec:
    selector:
        matchLabels:
            app: mongo
    template:
        metadata:
            labels:
                app: mongo
        spec:
            containers:
              - name: mongo
                image: mongo:8.0.4
                ports:
                  - containerPort: 27017
                volumeMounts:
                  - name: mongo-storage-volume
                    mountPath: /var/lib/mongo
                env:
                  - name: MONGO_INITDB_ROOT_PASSWORD
                    value: example
                  - name: MONGO_INITDB_ROOT_USERNAME
                    value: root


            volumes:
              - name: mongo-storage-volume
                persistentVolumeClaim:
                    claimName: mongo-storage

---
# NOTE: k3s имеет встроенный дефолтный storage
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#     name: mongo-pv
# spec:
#     # storageClassName: manual
#     accessModes:
#       - ReadWriteOnce
#     capacity:
#         storage: 1Gi
#
# ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mongo-storage
spec:
    accessModes:
      - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi

