services:
    k3s-server:
        image: rancher/k3s:v1.35.3-k3s1
        privileged: true
        ports:
            - 6443:6443
        command: server --token-file /k3s-token.txt
        volumes:
            - ./k3s-token.txt:/k3s-token.txt:ro

    agent:
        image: rancher/k3s:v1.35.3-k3s1
        network_mode: host
        privileged: true
        command: agent --token-file /k3s-token.txt --server https://localhost:6443
        volumes:
            - ./k3s-token.txt:/k3s-token.txt:ro

    # registry:
    #     image: registry:3
    #     ports: 
    #         - 5000:5000
    #     environment:
    #         OTEL_TRACES_EXPORTER: none 
    #         REGISTRY_LOG_LEVEL: info
    #         REGISTRY_HTTP_TLS_CERTIFICATE: /certs/fullchain.pem
    #         REGISTRY_HTTP_TLS_KEY: /certs/privkey.pem
    #         REGISTRY_AUTH: htpasswd
    #         REGISTRY_AUTH_HTPASSWD_PATH: /htpasswd
    #         REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    #     volumes:
    #         - ./certs:/certs
    #         - ./htpasswd:/htpasswd:ro
    #
